econ_ge:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: "{{ env_var('POSTGRES_HOST_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
